from app.models.monitoring.anekdot import MonitoringAnekdot
from app.models.monitoring.asesmen_awal import MonitoringAsesmenAwal
from app.models.monitoring.indikator import MonitoringIndikator
from app.models.monitoring.karya import MonitoringKarya
from app.models.monitoring.kegiatan import MonitoringKegiatan
from app.models.monitoring.kktp import MonitoringKKTP
from app.models.monitoring.monitoring import Monitoring
from app.models.monitoring.rekomendasi import MonitoringRekomendasi
from app.models.monitoring.tp import MonitoringTP