from app.models.monitoring.siswa.anekdot import MonitoringAnekdot
from app.models.monitoring.siswa.indikator import MonitoringIndikator
from app.models.monitoring.siswa.karya import MonitoringKarya
from app.models.monitoring.siswa.rekomendasi import MonitoringRekomendasi
from app.models.monitoring.mingguan.kegiatan import MonitoringKegiatan
from app.models.monitoring.mingguan.kktp import MonitoringKKTP
from app.models.monitoring.mingguan.tp import MonitoringTP
from app.models.monitoring.mingguan.monitoring import MonitoringMingguan
from app.models.monitoring.mingguan.asesmen_awal import MonitoringAsesmenAwal