"""menambahkan model gelombang dan field observasi pendaftaran

Revision ID: 13e49eefdc91
Revises: 312029bf6e40
Create Date: 2026-04-25 16:38:20.767783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e49eefdc91'
down_revision = '312029bf6e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gelombang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('tanggal_mulai', sa.Date(), nullable=True),
    sa.Column('tanggal_selesai', sa.Date(), nullable=True),
    sa.Column('id_tahun', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_gelombang', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_observasi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jam_observasi', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('status_observasi', sa.Enum('belum', 'terjadwal', 'hadir', 'tidak_hadir', name='status_observasi_enum'), nullable=True))
        batch_op.create_foreign_key(None, 'gelombang', ['id_gelombang'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_observasi')
        batch_op.drop_column('jam_observasi')
        batch_op.drop_column('tanggal_observasi')
        batch_op.drop_column('id_gelombang')

    op.drop_table('gelombang')
    # ### end Alembic commands ###
