"""add status_berkas to pendaftaran

Revision ID: 1eb75f9a34a1
Revises: ac65da0a5e10
Create Date: 2026-05-20 17:32:33.931659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb75f9a34a1'
down_revision = 'ac65da0a5e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_berkas', sa.Enum('belum_upload', 'pending', 'verified', 'rejected', name='status_berkas_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_column('status_berkas')

    # ### end Alembic commands ###
