"""add monitoring tables

Revision ID: 26345ea9d8ba
Revises: 1eb75f9a34a1
Create Date: 2026-05-29 20:05:02.000366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26345ea9d8ba'
down_revision = '1eb75f9a34a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_mingguan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_kelas_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('minggu', sa.Integer(), nullable=False),
    sa.Column('topik', sa.String(length=150), nullable=False),
    sa.Column('sub_topik', sa.String(length=150), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('ringkasan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='status_monitoring_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['siswa_kelas_id'], ['siswa_kelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siswa_kelas_id', 'semester', 'minggu', name='unique_monitoring_siswa_per_minggu')
    )
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_mingguan_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_mingguan_siswa_kelas_id'), ['siswa_kelas_id'], unique=False)

    op.create_table('monitoring_asesmen_awal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('teknik', sa.String(length=100), nullable=False),
    sa.Column('rancangan_kegiatan', sa.Text(), nullable=False),
    sa.Column('hasil', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitoring_id')
    )
    op.create_table('monitoring_kegiatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_kegiatan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_kegiatan_monitoring_id'), ['monitoring_id'], unique=False)

    op.create_table('monitoring_rekomendasi_rumah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('elemen', sa.Enum('kesyuhadaan', 'nabp', 'jd', 'ddlmstrs', name='elemen_rekomendasi_enum'), nullable=False),
    sa.Column('tips', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_rekomendasi_rumah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_rekomendasi_rumah_monitoring_id'), ['monitoring_id'], unique=False)

    op.create_table('monitoring_tp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('elemen', sa.Enum('kesyuhadaan', 'nabp', 'jd', 'ddlmstrs', name='elemen_monitoring_enum'), nullable=False),
    sa.Column('tujuan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_tp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_tp_monitoring_id'), ['monitoring_id'], unique=False)

    op.create_table('monitoring_kktp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tp_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tp_id'], ['monitoring_tp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_kktp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_kktp_tp_id'), ['tp_id'], unique=False)

    op.create_table('monitoring_catatan_anekdot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('kktp_id', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kktp_id'], ['monitoring_kktp.id'], ),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_catatan_anekdot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_catatan_anekdot_kktp_id'), ['kktp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_catatan_anekdot_monitoring_id'), ['monitoring_id'], unique=False)

    op.create_table('monitoring_hasil_karya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('kktp_id', sa.Integer(), nullable=False),
    sa.Column('kegiatan', sa.String(length=150), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('analisa', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kktp_id'], ['monitoring_kktp.id'], ),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_hasil_karya', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_hasil_karya_kktp_id'), ['kktp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_hasil_karya_monitoring_id'), ['monitoring_id'], unique=False)

    op.create_table('monitoring_indikator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_id', sa.Integer(), nullable=False),
    sa.Column('kktp_id', sa.Integer(), nullable=False),
    sa.Column('muncul', sa.Boolean(), nullable=False),
    sa.Column('kejadian_teramati', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kktp_id'], ['monitoring_kktp.id'], ),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_indikator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_indikator_kktp_id'), ['kktp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_indikator_monitoring_id'), ['monitoring_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_indikator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_indikator_monitoring_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_indikator_kktp_id'))

    op.drop_table('monitoring_indikator')
    with op.batch_alter_table('monitoring_hasil_karya', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_hasil_karya_monitoring_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_hasil_karya_kktp_id'))

    op.drop_table('monitoring_hasil_karya')
    with op.batch_alter_table('monitoring_catatan_anekdot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_catatan_anekdot_monitoring_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_catatan_anekdot_kktp_id'))

    op.drop_table('monitoring_catatan_anekdot')
    with op.batch_alter_table('monitoring_kktp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_kktp_tp_id'))

    op.drop_table('monitoring_kktp')
    with op.batch_alter_table('monitoring_tp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_tp_monitoring_id'))

    op.drop_table('monitoring_tp')
    with op.batch_alter_table('monitoring_rekomendasi_rumah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_rekomendasi_rumah_monitoring_id'))

    op.drop_table('monitoring_rekomendasi_rumah')
    with op.batch_alter_table('monitoring_kegiatan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_kegiatan_monitoring_id'))

    op.drop_table('monitoring_kegiatan')
    op.drop_table('monitoring_asesmen_awal')
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_mingguan_siswa_kelas_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_mingguan_created_by'))

    op.drop_table('monitoring_mingguan')
    # ### end Alembic commands ###
