"""add field userid, status dan status pembayaran  table pendaftaran

Revision ID: 26f22a93d258
Revises: 44c149c3e70a
Create Date: 2026-04-17 15:16:27.770581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26f22a93d258'
down_revision = '44c149c3e70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'verified', 'accepted', 'rejected', name='status_pendaftaran_enum'), nullable=True))
        batch_op.add_column(sa.Column('status_pembayaran', sa.Enum('unpaid', 'pending', 'paid', 'failed', name='status_pembayaran_enum'), nullable=True))
        batch_op.alter_column('no_pendaftaran',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('no_pendaftaran',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.drop_column('status_pembayaran')
        batch_op.drop_column('status')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
