"""add bulan to monitoring mingguan unique constraint

Revision ID: 29c488e58572
Revises: 328c2a0a2b5b
Create Date: 2026-06-09 07:17:43.253620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c488e58572'
down_revision = '328c2a0a2b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulan', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_monitoring_mingguan_per_kelas'), type_='unique')
        batch_op.create_unique_constraint('unique_monitoring_mingguan_per_kelas', ['kelas_id', 'tahun_ajaran_id', 'semester', 'bulan', 'minggu'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.drop_constraint('unique_monitoring_mingguan_per_kelas', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_monitoring_mingguan_per_kelas'), ['kelas_id', 'tahun_ajaran_id', 'semester', 'minggu'])
        batch_op.drop_column('bulan')

    # ### end Alembic commands ###
