"""merubah model asesmen

Revision ID: 312029bf6e40
Revises: b91ca8342f55
Create Date: 2026-04-23 20:33:25.204492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '312029bf6e40'
down_revision = 'b91ca8342f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesmen_pertanyaan', schema=None) as batch_op:
        batch_op.drop_column('options')
        batch_op.drop_column('tipe')
        batch_op.drop_column('is_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesmen_pertanyaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipe', mysql.ENUM('text', 'textarea', 'radio', 'checkbox', 'select', 'number'), nullable=True))
        batch_op.add_column(sa.Column('options', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###
