"""add token expiration fields to users table

Revision ID: 328c2a0a2b5b
Revises: a296549ef7da
Create Date: 2026-06-08 20:57:56.932091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328c2a0a2b5b'
down_revision = 'a296549ef7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('verification_token_expires_at')

    # ### end Alembic commands ###
