"""add snapshot fields to kpsp jawaban

Revision ID: 357be84780c0
Revises: a4257625f0e9
Create Date: 2026-06-03 22:41:31.569723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357be84780c0'
down_revision = 'a4257625f0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpsp_jawaban', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_usia_bulan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('snapshot_aspek_perkembangan', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('snapshot_kemampuan_anak', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('snapshot_urutan', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpsp_jawaban', schema=None) as batch_op:
        batch_op.drop_column('snapshot_urutan')
        batch_op.drop_column('snapshot_kemampuan_anak')
        batch_op.drop_column('snapshot_aspek_perkembangan')
        batch_op.drop_column('snapshot_usia_bulan')

    # ### end Alembic commands ###
