"""add academic fields to siswa and tahun_ajaran

Revision ID: 37f8c2354c09
Revises: a5b30cc47d8d
Create Date: 2026-05-18 06:17:44.891148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37f8c2354c09'
down_revision = 'a5b30cc47d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nisn', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('nis'))
        batch_op.create_unique_constraint(None, ['nisn'])
        batch_op.drop_column('nis')

    with op.batch_alter_table('tahun_ajaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_mulai', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('tanggal_selesai', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tahun_ajaran', schema=None) as batch_op:
        batch_op.drop_column('tanggal_selesai')
        batch_op.drop_column('tanggal_mulai')

    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nis', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('nis'), ['nis'], unique=True)
        batch_op.drop_column('nisn')

    # ### end Alembic commands ###
