"""add model siswa

Revision ID: 3cd5289fa0cb
Revises: 26f22a93d258
Create Date: 2026-04-17 15:41:17.862716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd5289fa0cb'
down_revision = '26f22a93d258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=True),
    sa.Column('nis', sa.String(length=20), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('aktif', 'lulus', 'keluar', name='status_siswa_enum'), nullable=True),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_peserta'),
    sa.UniqueConstraint('nis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    # ### end Alembic commands ###
