"""add field status table peserta didik

Revision ID: 44c149c3e70a
Revises: bba34c8ca699
Create Date: 2026-04-17 15:14:30.005764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c149c3e70a'
down_revision = 'bba34c8ca699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peserta_didik', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('calon', 'aktif', 'nonaktif', name='status_peserta_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peserta_didik', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
