"""init database

Revision ID: 51210aa18731
Revises: 
Create Date: 2026-05-29 22:25:47.587825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51210aa18731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=False),
    sa.Column('rt', sa.String(length=3), nullable=False),
    sa.Column('rw', sa.String(length=3), nullable=False),
    sa.Column('kelurahan', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=False),
    sa.Column('kode_pos', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asesmen_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpph_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor')
    )
    op.create_table('kpsp_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usia_bulan', sa.Integer(), nullable=False),
    sa.Column('aspek_perkembangan', sa.String(length=100), nullable=False),
    sa.Column('kemampuan_anak', sa.Text(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpsp_pertanyaan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpsp_pertanyaan_usia_bulan'), ['usia_bulan'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tahun_ajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_mulai', sa.Integer(), nullable=False),
    sa.Column('tahun_selesai', sa.Integer(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun_mulai', 'tahun_selesai', name='unique_tahun_ajaran')
    )
    op.create_table('gelombang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun_ajaran_id', 'nama', name='unique_gelombang_per_tahun')
    )
    with op.batch_alter_table('gelombang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gelombang_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('jenjang', sa.Enum('kb', 'tk', name='jenjang_kelas_enum'), nullable=False),
    sa.Column('kelompok', sa.Enum('a', 'b', name='kelompok_kelas_enum'), nullable=True),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kelas_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guru_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('peran', sa.Enum('wali_kelas', 'pendamping', name='peran_guru_kelas_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guru_id', 'kelas_id', 'tahun_ajaran_id', name='unique_guru_kelas_per_tahun')
    )
    with op.batch_alter_table('guru_kelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guru_kelas_guru_id'), ['guru_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guru_kelas_kelas_id'), ['kelas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guru_kelas_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('monitoring_mingguan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('minggu', sa.Integer(), nullable=False),
    sa.Column('topik', sa.String(length=150), nullable=False),
    sa.Column('sub_topik', sa.String(length=150), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='status_monitoring_mingguan_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kelas_id', 'tahun_ajaran_id', 'semester', 'minggu', name='unique_monitoring_mingguan_per_kelas')
    )
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_mingguan_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_mingguan_kelas_id'), ['kelas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_mingguan_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('peserta_didik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alamat_domisili_id', sa.Integer(), nullable=True),
    sa.Column('alamat_kk_id', sa.Integer(), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('nama_panggilan', sa.String(length=100), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P', name='jk_enum'), nullable=False),
    sa.Column('kewarganegaraan', sa.String(length=50), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('no_kk', sa.String(length=16), nullable=False),
    sa.Column('no_akta', sa.String(length=25), nullable=False),
    sa.Column('agama', sa.Enum('islam', 'kristen', 'katolik', 'hindu', 'buddha', 'konghucu', name='agama_enum'), nullable=False),
    sa.Column('no_telp', sa.String(length=20), nullable=False),
    sa.Column('anak_ke', sa.Integer(), nullable=False),
    sa.Column('jumlah_saudara', sa.Integer(), nullable=False),
    sa.Column('bahasa', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alamat_domisili_id'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['alamat_kk_id'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('informasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('tinggal_dengan', sa.String(length=50), nullable=False),
    sa.Column('jarak_sekolah', sa.Float(), nullable=False),
    sa.Column('waktu_tempuh', sa.String(length=50), nullable=False),
    sa.Column('kendaraan', sa.String(length=50), nullable=False),
    sa.Column('pernah_sekolah', sa.Boolean(), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=150), nullable=True),
    sa.Column('npsn', sa.String(length=20), nullable=True),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('bakat', sa.String(length=100), nullable=True),
    sa.Column('hobi', sa.String(length=100), nullable=True),
    sa.Column('cita_cita', sa.String(length=100), nullable=True),
    sa.Column('sumber_informasi', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kesehatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('lingkar_kepala', sa.Float(), nullable=False),
    sa.Column('golongan_darah', sa.Enum('A', 'B', 'AB', 'O', name='golongan_darah_enum'), nullable=False),
    sa.Column('riwayat_penyakit', sa.Text(), nullable=False),
    sa.Column('alergi', sa.Text(), nullable=False),
    sa.Column('kebutuhan_khusus', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_asesmen_awal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_mingguan_id', sa.Integer(), nullable=False),
    sa.Column('teknik', sa.String(length=100), nullable=False),
    sa.Column('rancangan_kegiatan', sa.Text(), nullable=False),
    sa.Column('hasil', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_mingguan_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitoring_mingguan_id')
    )
    op.create_table('monitoring_kegiatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_mingguan_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_mingguan_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_kegiatan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_kegiatan_monitoring_mingguan_id'), ['monitoring_mingguan_id'], unique=False)

    op.create_table('monitoring_tp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_mingguan_id', sa.Integer(), nullable=False),
    sa.Column('elemen', sa.Enum('kesyuhadaan', 'nabp', 'jd', 'ddlmstrs', name='elemen_monitoring_enum'), nullable=False),
    sa.Column('tujuan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_mingguan_id'], ['monitoring_mingguan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_tp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_tp_monitoring_mingguan_id'), ['monitoring_mingguan_id'], unique=False)

    op.create_table('orang_tua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('alamat_id', sa.Integer(), nullable=True),
    sa.Column('tipe', sa.Enum('ayah', 'ibu', 'wali', name='tipe_orangtua_enum'), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('pendidikan', sa.Enum('SD', 'SMP', 'SMA', 'D1', 'D2', 'D3', 'D4', 'S1', 'S2', 'S3', name='pendidikan_enum'), nullable=False),
    sa.Column('pekerjaan', sa.String(length=50), nullable=False),
    sa.Column('pendapatan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('alamat_kantor', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alamat_id'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('gelombang_id', sa.Integer(), nullable=False),
    sa.Column('no_pendaftaran', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'verified', 'accepted', 'rejected', name='status_pendaftaran_enum'), nullable=False),
    sa.Column('status_pembayaran', sa.Enum('unpaid', 'pending', 'paid', 'failed', name='status_pembayaran_enum'), nullable=False),
    sa.Column('status_berkas', sa.Enum('belum_upload', 'pending', 'verified', 'rejected', name='status_berkas_enum'), nullable=False),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=False),
    sa.Column('jenis', sa.Enum('tk', 'kb', name='jenis_enum'), nullable=False),
    sa.Column('program', sa.Enum('reguler', 'halfday', 'fullday', name='program_enum'), nullable=False),
    sa.Column('observasi_at', sa.DateTime(), nullable=True),
    sa.Column('status_observasi', sa.Enum('belum', 'terjadwal', 'hadir', 'tidak_hadir', name='status_observasi_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gelombang_id'], ['gelombang.id'], ),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_pendaftaran')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('aktif', 'lulus', 'keluar', name='status_siswa_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siswa_peserta_id'), ['peserta_id'], unique=True)

    op.create_table('asesmen_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pendaftaran', sa.Integer(), nullable=True),
    sa.Column('id_pertanyaan', sa.Integer(), nullable=True),
    sa.Column('jawaban', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pendaftaran'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['id_pertanyaan'], ['asesmen_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dokumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('jenis_dokumen', sa.Enum('kk', 'akta', 'kia', 'foto', 'surat_pernyataan', 'bukti_pembayaran', name='jenis_dokumen_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dokumen_pendaftaran_id'), ['pendaftaran_id'], unique=False)

    op.create_table('gpph_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan_id', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['pertanyaan_id'], ['gpph_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gpph_jawaban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gpph_jawaban_pendaftaran_id'), ['pendaftaran_id'], unique=False)

    op.create_table('kpsp_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan_id', sa.Integer(), nullable=False),
    sa.Column('jawaban', sa.Enum('ya', 'tidak', name='jawaban_kpsp_enum'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['pertanyaan_id'], ['kpsp_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpsp_jawaban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpsp_jawaban_pendaftaran_id'), ['pendaftaran_id'], unique=False)

    op.create_table('monitoring_kktp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tp_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tp_id'], ['monitoring_tp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_kktp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_kktp_tp_id'), ['tp_id'], unique=False)

    op.create_table('siswa_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aktif', 'naik', 'tinggal', 'pindah', 'lulus', name='status_siswa_kelas_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siswa_id', 'tahun_ajaran_id', name='unique_siswa_per_tahun_ajaran')
    )
    with op.batch_alter_table('siswa_kelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siswa_kelas_kelas_id'), ['kelas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siswa_kelas_siswa_id'), ['siswa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siswa_kelas_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('monitoring_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_mingguan_id', sa.Integer(), nullable=False),
    sa.Column('siswa_kelas_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('ringkasan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='status_monitoring_siswa_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['monitoring_mingguan_id'], ['monitoring_mingguan.id'], ),
    sa.ForeignKeyConstraint(['siswa_kelas_id'], ['siswa_kelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitoring_mingguan_id', 'siswa_kelas_id', name='unique_monitoring_siswa_per_minggu')
    )
    with op.batch_alter_table('monitoring_siswa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_siswa_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_siswa_monitoring_mingguan_id'), ['monitoring_mingguan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_siswa_siswa_kelas_id'), ['siswa_kelas_id'], unique=False)

    op.create_table('monitoring_catatan_anekdot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_siswa_id', sa.Integer(), nullable=False),
    sa.Column('kktp_id', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kktp_id'], ['monitoring_kktp.id'], ),
    sa.ForeignKeyConstraint(['monitoring_siswa_id'], ['monitoring_siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_catatan_anekdot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_catatan_anekdot_kktp_id'), ['kktp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_catatan_anekdot_monitoring_siswa_id'), ['monitoring_siswa_id'], unique=False)

    op.create_table('monitoring_hasil_karya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_siswa_id', sa.Integer(), nullable=False),
    sa.Column('kktp_id', sa.Integer(), nullable=False),
    sa.Column('kegiatan', sa.String(length=150), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('analisa', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kktp_id'], ['monitoring_kktp.id'], ),
    sa.ForeignKeyConstraint(['monitoring_siswa_id'], ['monitoring_siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_hasil_karya', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_hasil_karya_kktp_id'), ['kktp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_hasil_karya_monitoring_siswa_id'), ['monitoring_siswa_id'], unique=False)

    op.create_table('monitoring_indikator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_siswa_id', sa.Integer(), nullable=False),
    sa.Column('kktp_id', sa.Integer(), nullable=False),
    sa.Column('muncul', sa.Boolean(), nullable=False),
    sa.Column('kejadian_teramati', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kktp_id'], ['monitoring_kktp.id'], ),
    sa.ForeignKeyConstraint(['monitoring_siswa_id'], ['monitoring_siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_indikator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_indikator_kktp_id'), ['kktp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_indikator_monitoring_siswa_id'), ['monitoring_siswa_id'], unique=False)

    op.create_table('monitoring_rekomendasi_rumah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_siswa_id', sa.Integer(), nullable=False),
    sa.Column('elemen', sa.Enum('kesyuhadaan', 'nabp', 'jd', 'ddlmstrs', name='elemen_rekomendasi_enum'), nullable=False),
    sa.Column('tips', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_siswa_id'], ['monitoring_siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_rekomendasi_rumah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_rekomendasi_rumah_monitoring_siswa_id'), ['monitoring_siswa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_rekomendasi_rumah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_rekomendasi_rumah_monitoring_siswa_id'))

    op.drop_table('monitoring_rekomendasi_rumah')
    with op.batch_alter_table('monitoring_indikator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_indikator_monitoring_siswa_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_indikator_kktp_id'))

    op.drop_table('monitoring_indikator')
    with op.batch_alter_table('monitoring_hasil_karya', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_hasil_karya_monitoring_siswa_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_hasil_karya_kktp_id'))

    op.drop_table('monitoring_hasil_karya')
    with op.batch_alter_table('monitoring_catatan_anekdot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_catatan_anekdot_monitoring_siswa_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_catatan_anekdot_kktp_id'))

    op.drop_table('monitoring_catatan_anekdot')
    with op.batch_alter_table('monitoring_siswa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_siswa_siswa_kelas_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_siswa_monitoring_mingguan_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_siswa_created_by'))

    op.drop_table('monitoring_siswa')
    with op.batch_alter_table('siswa_kelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siswa_kelas_tahun_ajaran_id'))
        batch_op.drop_index(batch_op.f('ix_siswa_kelas_siswa_id'))
        batch_op.drop_index(batch_op.f('ix_siswa_kelas_kelas_id'))

    op.drop_table('siswa_kelas')
    with op.batch_alter_table('monitoring_kktp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_kktp_tp_id'))

    op.drop_table('monitoring_kktp')
    with op.batch_alter_table('kpsp_jawaban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpsp_jawaban_pendaftaran_id'))

    op.drop_table('kpsp_jawaban')
    with op.batch_alter_table('gpph_jawaban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gpph_jawaban_pendaftaran_id'))

    op.drop_table('gpph_jawaban')
    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dokumen_pendaftaran_id'))

    op.drop_table('dokumen')
    op.drop_table('asesmen_jawaban')
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siswa_peserta_id'))

    op.drop_table('siswa')
    op.drop_table('pendaftaran')
    op.drop_table('orang_tua')
    with op.batch_alter_table('monitoring_tp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_tp_monitoring_mingguan_id'))

    op.drop_table('monitoring_tp')
    with op.batch_alter_table('monitoring_kegiatan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_kegiatan_monitoring_mingguan_id'))

    op.drop_table('monitoring_kegiatan')
    op.drop_table('monitoring_asesmen_awal')
    op.drop_table('kesehatan')
    op.drop_table('informasi')
    op.drop_table('peserta_didik')
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_mingguan_tahun_ajaran_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_mingguan_kelas_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_mingguan_created_by'))

    op.drop_table('monitoring_mingguan')
    with op.batch_alter_table('guru_kelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guru_kelas_tahun_ajaran_id'))
        batch_op.drop_index(batch_op.f('ix_guru_kelas_kelas_id'))
        batch_op.drop_index(batch_op.f('ix_guru_kelas_guru_id'))

    op.drop_table('guru_kelas')
    op.drop_table('users')
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kelas_tahun_ajaran_id'))

    op.drop_table('kelas')
    with op.batch_alter_table('gelombang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gelombang_tahun_ajaran_id'))

    op.drop_table('gelombang')
    op.drop_table('tahun_ajaran')
    op.drop_table('roles')
    with op.batch_alter_table('kpsp_pertanyaan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpsp_pertanyaan_usia_bulan'))

    op.drop_table('kpsp_pertanyaan')
    op.drop_table('gpph_pertanyaan')
    op.drop_table('asesmen_pertanyaan')
    op.drop_table('alamat')
    # ### end Alembic commands ###
