"""change guru kelas enum

Revision ID: 66bc602dfee8
Revises: 51210aa18731
Create Date: 2026-05-31 09:52:44.837698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66bc602dfee8'
down_revision = '51210aa18731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guru_kelas', schema=None) as batch_op:
        batch_op.alter_column('peran',
               existing_type=mysql.ENUM('wali_kelas', 'pendamping'),
               type_=sa.Enum('wali kelas', 'pendamping', name='peran_guru_kelas_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guru_kelas', schema=None) as batch_op:
        batch_op.alter_column('peran',
               existing_type=sa.Enum('wali kelas', 'pendamping', name='peran_guru_kelas_enum'),
               type_=mysql.ENUM('wali_kelas', 'pendamping'),
               existing_nullable=False)

    # ### end Alembic commands ###
