"""add kpsp_tables

Revision ID: 831c4dd72f6c
Revises: b3ae8693929c
Create Date: 2026-05-13 16:05:26.724915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831c4dd72f6c'
down_revision = 'b3ae8693929c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpsp_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usia_bulan', sa.Integer(), nullable=False),
    sa.Column('aspek_perkembangan', sa.String(length=100), nullable=False),
    sa.Column('kemampuan_anak', sa.Text(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpsp_pertanyaan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpsp_pertanyaan_usia_bulan'), ['usia_bulan'], unique=False)

    op.create_table('kpsp_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan_id', sa.Integer(), nullable=False),
    sa.Column('jawaban', sa.Enum('ya', 'tidak', name='jawaban_kpsp_enum'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['pertanyaan_id'], ['kpsp_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpsp_jawaban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpsp_jawaban_pendaftaran_id'), ['pendaftaran_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpsp_jawaban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpsp_jawaban_pendaftaran_id'))

    op.drop_table('kpsp_jawaban')
    with op.batch_alter_table('kpsp_pertanyaan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpsp_pertanyaan_usia_bulan'))

    op.drop_table('kpsp_pertanyaan')
    # ### end Alembic commands ###
