"""change semester and minggu to enum

Revision ID: a271ac1331a1
Revises: c6544063c35d
Create Date: 2026-06-01 19:28:27.945455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a271ac1331a1'
down_revision = 'c6544063c35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('ganjil', 'genap', name='semester_monitoring_mingguan_enum'),
               existing_nullable=False)
        batch_op.alter_column('minggu',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('1', '2', '3', '4', name='minggu_monitoring_mingguan_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_mingguan', schema=None) as batch_op:
        batch_op.alter_column('minggu',
               existing_type=sa.Enum('1', '2', '3', '4', name='minggu_monitoring_mingguan_enum'),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('semester',
               existing_type=sa.Enum('ganjil', 'genap', name='semester_monitoring_mingguan_enum'),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
