"""refactor gpph with snapshot and soft delete

Revision ID: a296549ef7da
Revises: 357be84780c0
Create Date: 2026-06-04 07:15:36.376951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a296549ef7da'
down_revision = '357be84780c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpph_jawaban', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_urutan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('snapshot_pertanyaan', sa.Text(), nullable=False))

    with op.batch_alter_table('gpph_pertanyaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urutan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('nomor'))
        batch_op.drop_column('nomor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpph_pertanyaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('nomor'), ['nomor'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('urutan')

    with op.batch_alter_table('gpph_jawaban', schema=None) as batch_op:
        batch_op.drop_column('snapshot_pertanyaan')
        batch_op.drop_column('snapshot_urutan')

    # ### end Alembic commands ###
