"""add is_active to kpsp pertanyaan

Revision ID: a4257625f0e9
Revises: 1b3f5a3cd103
Create Date: 2026-06-03 21:41:12.619646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4257625f0e9'
down_revision = '1b3f5a3cd103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpsp_pertanyaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpsp_pertanyaan', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
