"""add academic models

Revision ID: a5b30cc47d8d
Revises: 831c4dd72f6c
Create Date: 2026-05-18 05:40:05.085290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5b30cc47d8d'
down_revision = '831c4dd72f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('jenjang', sa.Enum('kb', 'tk', name='jenjang_kelas_enum'), nullable=False),
    sa.Column('kelompok', sa.Enum('a', 'b', name='kelompok_kelas_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kelas_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('guru_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('peran', sa.Enum('wali_kelas', 'pendamping', name='peran_guru_kelas_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guru_id', 'kelas_id', 'tahun_ajaran_id', name='unique_guru_kelas_per_tahun')
    )
    with op.batch_alter_table('guru_kelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guru_kelas_guru_id'), ['guru_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guru_kelas_kelas_id'), ['kelas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guru_kelas_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    op.create_table('siswa_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aktif', 'naik', 'tinggal', 'pindah', 'lulus', name='status_siswa_kelas_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siswa_id', 'tahun_ajaran_id', name='unique_siswa_per_tahun_ajaran')
    )
    with op.batch_alter_table('siswa_kelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siswa_kelas_kelas_id'), ['kelas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siswa_kelas_siswa_id'), ['siswa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siswa_kelas_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('siswa_ibfk_1'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('id_peserta'))
    
        batch_op.add_column(sa.Column('peserta_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
    
        batch_op.alter_column(
            'tanggal_masuk',
            existing_type=sa.DATE(),
            nullable=False
        )
    
        batch_op.alter_column(
            'status',
            existing_type=mysql.ENUM('aktif', 'lulus', 'keluar'),
            nullable=False
        )
    
        batch_op.create_index(
            batch_op.f('ix_siswa_peserta_id'),
            ['peserta_id'],
            unique=True
        )
    
        batch_op.create_foreign_key(
            None,
            'peserta_didik',
            ['peserta_id'],
            ['id']
        )
    
        batch_op.drop_column('id_peserta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_peserta', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('siswa_ibfk_1'), 'peserta_didik', ['id_peserta'], ['id'])
        batch_op.drop_index(batch_op.f('ix_siswa_peserta_id'))
        batch_op.create_index(batch_op.f('id_peserta'), ['id_peserta'], unique=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('aktif', 'lulus', 'keluar'),
               nullable=True)
        batch_op.alter_column('tanggal_masuk',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('peserta_id')

    with op.batch_alter_table('siswa_kelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siswa_kelas_tahun_ajaran_id'))
        batch_op.drop_index(batch_op.f('ix_siswa_kelas_siswa_id'))
        batch_op.drop_index(batch_op.f('ix_siswa_kelas_kelas_id'))

    op.drop_table('siswa_kelas')
    with op.batch_alter_table('guru_kelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guru_kelas_tahun_ajaran_id'))
        batch_op.drop_index(batch_op.f('ix_guru_kelas_kelas_id'))
        batch_op.drop_index(batch_op.f('ix_guru_kelas_guru_id'))

    op.drop_table('guru_kelas')
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kelas_tahun_ajaran_id'))

    op.drop_table('kelas')
    # ### end Alembic commands ###
