"""add kapasitas to kelas

Revision ID: b2c70ef0fd64
Revises: 37f8c2354c09
Create Date: 2026-05-18 17:07:30.912757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c70ef0fd64'
down_revision = '37f8c2354c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kapasitas', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_column('kapasitas')

    # ### end Alembic commands ###
