"""add gpph tables

Revision ID: b3ae8693929c
Revises: c6f9e20bd2d8
Create Date: 2026-05-12 23:56:03.952977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ae8693929c'
down_revision = 'c6f9e20bd2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpph_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor')
    )
    op.create_table('gpph_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan_id', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['pertanyaan_id'], ['gpph_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gpph_jawaban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gpph_jawaban_pendaftaran_id'), ['pendaftaran_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpph_jawaban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gpph_jawaban_pendaftaran_id'))

    op.drop_table('gpph_jawaban')
    op.drop_table('gpph_pertanyaan')
    # ### end Alembic commands ###
