"""add model asesmen

Revision ID: b91ca8342f55
Revises: 3cd5289fa0cb
Create Date: 2026-04-23 14:06:03.290184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91ca8342f55'
down_revision = '3cd5289fa0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesmen_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('tipe', sa.Enum('text', 'textarea', 'radio', 'checkbox', 'select', 'number', name='tipe_asesmen_enum'), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asesmen_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pendaftaran', sa.Integer(), nullable=True),
    sa.Column('id_pertanyaan', sa.Integer(), nullable=True),
    sa.Column('jawaban', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pendaftaran'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['id_pertanyaan'], ['asesmen_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asesmen_jawaban')
    op.drop_table('asesmen_pertanyaan')
    # ### end Alembic commands ###
