"""add models pendaftaran

Revision ID: bba34c8ca699
Revises: ae6babe0b027
Create Date: 2026-04-17 07:30:25.221640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba34c8ca699'
down_revision = 'ae6babe0b027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=True),
    sa.Column('rt', sa.String(length=5), nullable=True),
    sa.Column('rw', sa.String(length=5), nullable=True),
    sa.Column('desa', sa.String(length=100), nullable=True),
    sa.Column('kecamatan', sa.String(length=100), nullable=True),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('kode_pos', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahun_ajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_mulai', sa.Integer(), nullable=True),
    sa.Column('tahun_selesai', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_pendaftaran', sa.String(length=3), nullable=True),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=True),
    sa.Column('jenis', sa.Enum('tk', 'kb', name='jenis_enum'), nullable=True),
    sa.Column('program', sa.Enum('reguler', 'halfday', 'fullday', name='program_enum'), nullable=True),
    sa.Column('id_tahun', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_pendaftaran')
    )
    op.create_table('dokumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pendaftaran', sa.Integer(), nullable=True),
    sa.Column('jenis_dokumen', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pendaftaran'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peserta_didik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pendaftaran', sa.Integer(), nullable=True),
    sa.Column('id_alamat_domisili', sa.Integer(), nullable=True),
    sa.Column('id_alamat_kk', sa.Integer(), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=True),
    sa.Column('nama_panggilan', sa.String(length=100), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=True),
    sa.Column('kewarganegaraan', sa.String(length=50), nullable=True),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('no_kk', sa.String(length=20), nullable=True),
    sa.Column('no_akta', sa.String(length=20), nullable=True),
    sa.Column('agama', sa.String(length=50), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('anak_ke', sa.Integer(), nullable=True),
    sa.Column('jumlah_saudara', sa.Integer(), nullable=True),
    sa.Column('bahasa', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_alamat_domisili'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['id_alamat_kk'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['id_pendaftaran'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=True),
    sa.Column('tinggal_dengan', sa.String(length=50), nullable=True),
    sa.Column('jarak_sekolah', sa.Float(), nullable=True),
    sa.Column('waktu_tempuh', sa.String(length=50), nullable=True),
    sa.Column('kendaraan', sa.String(length=50), nullable=True),
    sa.Column('pernah_sekolah', sa.Boolean(), nullable=True),
    sa.Column('nama_sekolah', sa.String(length=150), nullable=True),
    sa.Column('npsn', sa.String(length=20), nullable=True),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('bakat', sa.String(length=100), nullable=True),
    sa.Column('hobi', sa.String(length=100), nullable=True),
    sa.Column('cita_cita', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kesehatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=True),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('tinggi_badan', sa.Float(), nullable=True),
    sa.Column('lingkar_kepala', sa.Float(), nullable=True),
    sa.Column('golongan_darah', sa.String(length=5), nullable=True),
    sa.Column('riwayat_penyakit', sa.Text(), nullable=True),
    sa.Column('alergi', sa.Text(), nullable=True),
    sa.Column('kebutuhan_khusus', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orang_tua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=True),
    sa.Column('id_alamat', sa.Integer(), nullable=True),
    sa.Column('tipe', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=150), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('pendidikan', sa.String(length=50), nullable=True),
    sa.Column('pekerjaan', sa.String(length=50), nullable=True),
    sa.Column('pendapatan', sa.Float(), nullable=True),
    sa.Column('alamat_kantor', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_alamat'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orang_tua')
    op.drop_table('kesehatan')
    op.drop_table('informasi')
    op.drop_table('peserta_didik')
    op.drop_table('dokumen')
    op.drop_table('pendaftaran')
    op.drop_table('tahun_ajaran')
    op.drop_table('alamat')
    # ### end Alembic commands ###
