"""menyesuiakan tipe data

Revision ID: c6f9e20bd2d8
Revises: 694084bb33a5
Create Date: 2026-05-12 08:10:47.659803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6f9e20bd2d8'
down_revision = '694084bb33a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alamat', schema=None) as batch_op:
        batch_op.alter_column('rt',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('rw',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('kode_pos',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_dokumen_pendaftaran_id'), ['pendaftaran_id'], unique=False)

    with op.batch_alter_table('gelombang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gelombang_tahun_ajaran_id'), ['tahun_ajaran_id'], unique=False)

    with op.batch_alter_table('informasi', schema=None) as batch_op:
        batch_op.alter_column('tinggal_dengan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('jarak_sekolah',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('waktu_tempuh',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('kendaraan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('kesehatan', schema=None) as batch_op:
        batch_op.alter_column('berat_badan',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('tinggi_badan',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('lingkar_kepala',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('golongan_darah',
               existing_type=mysql.ENUM('A', 'B', 'AB', 'O'),
               nullable=False)
        batch_op.alter_column('riwayat_penyakit',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('alergi',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('kebutuhan_khusus',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.JSON(),
               nullable=False)

    with op.batch_alter_table('orang_tua', schema=None) as batch_op:
        batch_op.alter_column('pendapatan',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('peserta_didik', schema=None) as batch_op:
        batch_op.alter_column('no_telp',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peserta_didik', schema=None) as batch_op:
        batch_op.alter_column('no_telp',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('orang_tua', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('pendapatan',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True)

    with op.batch_alter_table('kesehatan', schema=None) as batch_op:
        batch_op.alter_column('kebutuhan_khusus',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('alergi',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('riwayat_penyakit',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('golongan_darah',
               existing_type=mysql.ENUM('A', 'B', 'AB', 'O'),
               nullable=True)
        batch_op.alter_column('lingkar_kepala',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('tinggi_badan',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('berat_badan',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('informasi', schema=None) as batch_op:
        batch_op.alter_column('kendaraan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('waktu_tempuh',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('jarak_sekolah',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('tinggal_dengan',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('gelombang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gelombang_tahun_ajaran_id'))

    with op.batch_alter_table('dokumen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dokumen_pendaftaran_id'))
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('alamat', schema=None) as batch_op:
        batch_op.alter_column('kode_pos',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('rw',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('rt',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
