"""initial schema

Revision ID: ced8d5c2c3d3
Revises: 
Create Date: 2026-05-09 23:22:24.747580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced8d5c2c3d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=False),
    sa.Column('rt', sa.String(length=5), nullable=False),
    sa.Column('rw', sa.String(length=5), nullable=False),
    sa.Column('kelurahan', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=False),
    sa.Column('kode_pos', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asesmen_pertanyaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tahun_ajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_mulai', sa.Integer(), nullable=False),
    sa.Column('tahun_selesai', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun_mulai', 'tahun_selesai', name='unique_tahun_ajaran')
    )
    op.create_table('gelombang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun_ajaran_id', 'nama', name='unique_gelombang_per_tahun')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('peserta_didik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alamat_domisili_id', sa.Integer(), nullable=True),
    sa.Column('alamat_kk_id', sa.Integer(), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('nama_panggilan', sa.String(length=100), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P', name='jk_enum'), nullable=False),
    sa.Column('kewarganegaraan', sa.String(length=50), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('no_kk', sa.String(length=16), nullable=False),
    sa.Column('no_akta', sa.String(length=25), nullable=False),
    sa.Column('agama', sa.Enum('islam', 'kristen', 'katolik', 'hindu', 'buddha', 'konghucu', name='agama_enum'), nullable=False),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('anak_ke', sa.Integer(), nullable=False),
    sa.Column('jumlah_saudara', sa.Integer(), nullable=False),
    sa.Column('bahasa', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alamat_domisili_id'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['alamat_kk_id'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('informasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('tinggal_dengan', sa.String(length=50), nullable=True),
    sa.Column('jarak_sekolah', sa.Float(), nullable=True),
    sa.Column('waktu_tempuh', sa.String(length=50), nullable=True),
    sa.Column('kendaraan', sa.String(length=50), nullable=True),
    sa.Column('pernah_sekolah', sa.Boolean(), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=150), nullable=True),
    sa.Column('npsn', sa.String(length=20), nullable=True),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('bakat', sa.String(length=100), nullable=True),
    sa.Column('hobi', sa.String(length=100), nullable=True),
    sa.Column('cita_cita', sa.String(length=100), nullable=True),
    sa.Column('sumber_informasi', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kesehatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('tinggi_badan', sa.Float(), nullable=True),
    sa.Column('lingkar_kepala', sa.Float(), nullable=True),
    sa.Column('golongan_darah', sa.Enum('A', 'B', 'AB', 'O', name='golongan_darah_enum'), nullable=True),
    sa.Column('riwayat_penyakit', sa.Text(), nullable=True),
    sa.Column('alergi', sa.Text(), nullable=True),
    sa.Column('kebutuhan_khusus', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orang_tua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('alamat_id', sa.Integer(), nullable=True),
    sa.Column('tipe', sa.Enum('ayah', 'ibu', 'wali', name='tipe_orangtua_enum'), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('pendidikan', sa.Enum('SD', 'SMP', 'SMA', 'D1', 'D2', 'D3', 'D4', 'S1', 'S2', 'S3', name='pendidikan_enum'), nullable=False),
    sa.Column('pekerjaan', sa.String(length=50), nullable=False),
    sa.Column('pendapatan', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('alamat_kantor', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alamat_id'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('gelombang_id', sa.Integer(), nullable=False),
    sa.Column('no_pendaftaran', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'verified', 'accepted', 'rejected', name='status_pendaftaran_enum'), nullable=False),
    sa.Column('status_pembayaran', sa.Enum('unpaid', 'pending', 'paid', 'failed', name='status_pembayaran_enum'), nullable=False),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=False),
    sa.Column('jenis', sa.Enum('tk', 'kb', name='jenis_enum'), nullable=False),
    sa.Column('program', sa.Enum('reguler', 'halfday', 'fullday', name='program_enum'), nullable=False),
    sa.Column('observasi_at', sa.DateTime(), nullable=True),
    sa.Column('status_observasi', sa.Enum('belum', 'terjadwal', 'hadir', 'tidak_hadir', name='status_observasi_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gelombang_id'], ['gelombang.id'], ),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_didik.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_pendaftaran')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=True),
    sa.Column('nis', sa.String(length=20), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('aktif', 'lulus', 'keluar', name='status_siswa_enum'), nullable=True),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta_didik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_peserta'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('asesmen_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pendaftaran', sa.Integer(), nullable=True),
    sa.Column('id_pertanyaan', sa.Integer(), nullable=True),
    sa.Column('jawaban', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pendaftaran'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['id_pertanyaan'], ['asesmen_pertanyaan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dokumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('jenis_dokumen', sa.Enum('kk', 'akta', 'kia', 'foto', 'surat_pernyataan', name='jenis_dokumen_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokumen')
    op.drop_table('asesmen_jawaban')
    op.drop_table('siswa')
    op.drop_table('pendaftaran')
    op.drop_table('orang_tua')
    op.drop_table('kesehatan')
    op.drop_table('informasi')
    op.drop_table('peserta_didik')
    op.drop_table('users')
    op.drop_table('gelombang')
    op.drop_table('tahun_ajaran')
    op.drop_table('roles')
    op.drop_table('asesmen_pertanyaan')
    op.drop_table('alamat')
    # ### end Alembic commands ###
