"""add nama_kelompok tabel kelas

Revision ID: d09f98f9ff01
Revises: b2c70ef0fd64
Create Date: 2026-05-18 22:16:06.216022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09f98f9ff01'
down_revision = 'b2c70ef0fd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_kelompok', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_column('nama_kelompok')

    # ### end Alembic commands ###
