"""delete nama kelompok class field

Revision ID: d68e563dc2c7
Revises: d09f98f9ff01
Create Date: 2026-05-19 07:20:53.981533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd68e563dc2c7'
down_revision = 'd09f98f9ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_column('nama_kelompok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_kelompok', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
