"""ubah tanggal daftar dan gelombang nullable

Revision ID: de30a39993da
Revises: 29c488e58572
Create Date: 2026-06-10 14:28:06.613785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de30a39993da'
down_revision = '29c488e58572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.alter_column('gelombang_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tanggal_daftar',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.alter_column('tanggal_daftar',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('gelombang_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
